export default {
    'a': 'Link',
    'article': 'Article',
    'b': 'Text',
    'blockquote': 'Quote',
    'button': 'Button',
    'cite': 'Quote',
    'canvas': 'Image',
    'code': 'Code',
    'form': 'Form',
    'h1': 'Title',
    'h2': 'Text',
    'h3': 'Text',
    'h4': 'Text',
    'h5': 'Text',
    'h6': 'Text',
    'img': 'Image',
    'svg': 'Image',
    'input': 'Input Field',
    'label': 'Label',
    'li': 'Line Item',
    'link': 'Link',
    'map': 'Map',
    'nav': 'Menu',
    'picture': 'Picture',
    'progress': 'Progress Bar',
    'q': 'Quote',
    'table': 'Table',
    'title': 'Title',
    'video': 'Video',
}
